spring.:
  application:
    name: benchmark

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA:public}&search_path==${POSTGRES_SCHEMA:public}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

client:
  config:
    retry:
      minPeriod: 1000
      maxPeriod: 3000
      maxAttempts: 5
  producer:
    url: http://localhost:8050
  kafka:
    url: http://localhost:8020/kafka-consumer
  rabbit:
    url: http://localhost:8030/rabbitmq-consumer
  redis:
    url: http://localhost:8040/redis-consumer

benchmark:
  files:
    energy-file: "energy.txt"
    monitoring-file: "results.csv"
